<?php

namespace App\Http\Middleware;

use Closure;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\Response;

class EnsureProfileComplete
{
    /**
     * Handle an incoming request.
     *
     * @param  \Closure(\Illuminate\Http\Request): (\Symfony\Component\HttpFoundation\Response)  $next
     */
    public function handle(Request $request, Closure $next): Response
    {
        $user = $request->user();

        if (!$user) {
            return $next($request);
        }

        // Check for "default" names generated by AuthService
        $isDefaultName = false;
        if (preg_match('/^User \d{4}$/', $user->name)) {
            $isDefaultName = true;
        } elseif ($user->email && $user->name === explode('@', $user->email)[0]) {
            $isDefaultName = true;
        }

        if ($isDefaultName || empty($user->name) || empty($user->email) || empty($user->phone)) {
            // Prevent infinite loop if already on the onboarding pages
            if (
                !$request->routeIs('onboarding.*') && 
                !$request->routeIs('profile.update') && 
                !$request->routeIs('logout')
            ) {
                return redirect()->route('onboarding.show');
            }
        }

        return $next($request);
    }
}
