<?php

namespace App\Http\Middleware;

use Closure;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Log;
use Symfony\Component\HttpFoundation\Response;

class EnsureProfileComplete
{
    /**
     * Handle an incoming request.
     *
     * @param  Closure(Request): (Response)  $next
     */
    public function handle(Request $request, Closure $next): Response
    {
        $user = $request->user();

        if (! $user) {
            return $next($request);
        }

        // Skip profile gating while an admin is impersonating — support staff
        // must be able to see the account as-is, not be forced through onboarding.
        if ($request->session()->has('impersonator_id')) {
            Log::debug('impersonation.profile_gate_skipped', [
                'user_id' => $user->id,
                'route' => $request->route()?->getName(),
                'session_id' => $request->session()->getId(),
            ]);

            return $next($request);
        }

        // Check for "default" names generated by AuthService
        $isDefaultName = false;
        if (preg_match('/^User \d{4}$/', $user->name)) {
            $isDefaultName = true;
        } elseif ($user->email && $user->name === explode('@', $user->email)[0]) {
            $isDefaultName = true;
        }

        if ($isDefaultName || empty($user->name) || empty($user->email) || empty($user->phone)) {
            // Prevent infinite loop if already on the onboarding pages
            if (
                ! $request->routeIs('onboarding.*') &&
                ! $request->routeIs('profile.update') &&
                ! $request->routeIs('logout')
            ) {
                return redirect()->route('onboarding.show');
            }
        }

        return $next($request);
    }
}
