export const adminTexts = {
    id: {
        brand: 'Admin Panel',
        impersonating: 'Anda sedang menyamar sebagai pengguna lain.',
        stop_impersonating: 'Kembali ke admin',
        nav: {
            dashboard: 'Dashboard',
            analytics: 'Analitik',
            users: 'Pengguna',
            settings: 'Pengaturan',
            categories: 'Kategori',
            cities: 'Kota',
            packages: 'Paket WhatsApp',
            back_to_app: 'Ke Aplikasi',
            logout: 'Keluar',
        },
        login: {
            title: 'Login Admin',
            subtitle: 'Masuk dengan email & password, lalu verifikasi OTP.',
            email: 'Email',
            password: 'Password',
            submit: 'Lanjut',
            processing: 'Memproses...',
        },
        otp: {
            title: 'Verifikasi OTP Admin',
            subtitle: 'Masukkan 6 digit kode yang dikirim ke email admin.',
            submit: 'Verifikasi',
            processing: 'Memverifikasi...',
            resend_title: 'Tidak menerima kode?',
            resend_email: 'Kirim ulang via Email',
            resend_whatsapp: 'Kirim via WhatsApp',
            sending: 'Mengirim...',
            wait: 'Kirim ulang dalam {timer}s',
            change_account: 'Ganti akun admin',
        },
        dashboard: {
            title: 'Ringkasan Platform',
            users: 'Pengguna',
            organizers: 'Organizer',
            attendees: 'Peserta',
            events: 'Event',
            published: 'Published',
            draft: 'Draft',
            bookings: 'Booking',
            confirmed: 'Terkonfirmasi',
            revenue: 'Pendapatan',
            quota_sold: 'Kuota WA Terjual',
        },
        analytics: {
            title: 'Analitik Platform',
            period_week: 'Mingguan',
            period_month: 'Bulanan',
            period_year: 'Tahunan',
            gross_revenue: 'Pendapatan Kotor',
            platform_revenue: 'Pendapatan Platform',
            organizer_revenue: 'Pendapatan Organizer',
            total_events: 'Event',
            total_bookings: 'Booking',
            visits: 'Kunjungan',
            events_chart: 'Event Dibuat',
            organizer_chart: 'Pendapatan Organizer',
            platform_chart: 'Pendapatan Platform',
            categories_title: 'Breakdown Kategori',
            col_category: 'Kategori',
            col_events: 'Event',
            col_share: 'Porsi',
            most_popular: 'Event Terpopuler',
            worst_performing: 'Event Terburuk',
            cancelled_events: 'Event Dibatalkan',
            countries: 'Asal Negara',
            cities: 'Asal Kota',
            devices: 'Perangkat',
            os: 'Sistem Operasi',
            realtime_title: 'Realtime',
            realtime_active: 'Aktif ({minutes} menit terakhir)',
            realtime_unique: 'Pengunjung unik',
            realtime_recent: 'Aktivitas Terbaru',
            realtime_empty: 'Belum ada kunjungan dalam {minutes} menit terakhir.',
            col_event: 'Event',
            col_when: 'Waktu',
            daily_title: 'Kunjungan Harian (14 Hari)',
            daily_visits: 'Kunjungan',
            daily_unique: 'Unik',
            col_title: 'Event',
            col_bookings: 'Booking',
            col_revenue: 'Pendapatan',
            col_city: 'Kota',
            col_count: 'Jumlah',
            col_percent: 'Persen',
            col_date: 'Tanggal',
            empty: 'Belum ada data.',
        },
        users: {
            title: 'Pengguna',
            name: 'Nama',
            email: 'Email',
            roles: 'Role',
            actions: 'Aksi',
            impersonate: 'Menyamar',
            suspend: 'Tangguhkan',
            activate: 'Aktifkan',
            delete: 'Hapus',
            confirm_delete: 'Hapus pengguna ini?',
            empty: 'Belum ada pengguna.',
            impersonate_title: 'Konfirmasi Impersonate',
            impersonate_hint: 'Masukkan password admin Anda untuk melanjutkan sebagai {name}.',
            password_label: 'Password Admin',
            confirm: 'Masuk sebagai pengguna',
            cancel: 'Batal',
            search_placeholder: 'Cari nama atau email…',
            filter_role: 'Semua role',
            filter_status: 'Semua status',
            status_active: 'Aktif',
            status_suspended: 'Ditangguhkan',
            page_info: 'Halaman {page} dari {last} · {total} pengguna',
            prev: 'Sebelumnya',
            next: 'Berikutnya',
        },
        settings: {
            title: 'Pengaturan Platform',
            tabs: {
                general: 'Umum',
                payment: 'Payment Gateway',
                whatsapp: 'WhatsApp',
                fee: 'Fee Platform',
            },
            general_title: 'Pengaturan Umum',
            app_name: 'Nama Aplikasi',
            contact_center: 'Contact Center',
            contact_email: 'Email Kontak',
            payment_title: 'Payment Gateway',
            enabled: 'Aktif',
            provider: 'Provider',
            api_key: 'API Key',
            secret_key: 'Secret Key',
            secret_set: 'Tersimpan (biarkan kosong untuk tidak mengubah)',
            whatsapp_title: 'WhatsApp Provider',
            token: 'Token',
            sender: 'Sender',
            fee_title: 'Fee Platform',
            fee_type: 'Tipe',
            fee_fixed: 'Nominal tetap',
            fee_percent: 'Persentase (%)',
            fee_amount: 'Besaran',
            save: 'Simpan',
            saving: 'Menyimpan...',
        },
        catalog: {
            add: 'Tambah',
            save: 'Simpan',
            delete: 'Hapus',
            cancel: 'Batal',
            edit: 'Edit',
            name: 'Nama',
            slug: 'Slug',
            name_en: 'Nama (EN)',
            active: 'Aktif',
            quota: 'Kuota',
            amount: 'Harga',
            label: 'Label',
            empty: 'Belum ada data.',
        },
    },
    en: {
        brand: 'Admin Panel',
        impersonating: 'You are impersonating another user.',
        stop_impersonating: 'Back to admin',
        nav: {
            dashboard: 'Dashboard',
            analytics: 'Analytics',
            users: 'Users',
            settings: 'Settings',
            categories: 'Categories',
            cities: 'Cities',
            packages: 'WhatsApp Packages',
            back_to_app: 'Back to App',
            logout: 'Log out',
        },
        login: {
            title: 'Admin Login',
            subtitle: 'Sign in with email & password, then verify OTP.',
            email: 'Email',
            password: 'Password',
            submit: 'Continue',
            processing: 'Processing...',
        },
        otp: {
            title: 'Admin OTP Verification',
            subtitle: 'Enter the 6-digit code sent to the admin email.',
            submit: 'Verify',
            processing: 'Verifying...',
            resend_title: "Didn't receive a code?",
            resend_email: 'Resend via Email',
            resend_whatsapp: 'Send via WhatsApp',
            sending: 'Sending...',
            wait: 'Resend in {timer}s',
            change_account: 'Use a different admin account',
        },
        dashboard: {
            title: 'Platform Overview',
            users: 'Users',
            organizers: 'Organizers',
            attendees: 'Attendees',
            events: 'Events',
            published: 'Published',
            draft: 'Draft',
            bookings: 'Bookings',
            confirmed: 'Confirmed',
            revenue: 'Revenue',
            quota_sold: 'WA Quota Sold',
        },
        analytics: {
            title: 'Platform Analytics',
            period_week: 'Weekly',
            period_month: 'Monthly',
            period_year: 'Yearly',
            gross_revenue: 'Gross Revenue',
            platform_revenue: 'Platform Revenue',
            organizer_revenue: 'Organizer Revenue',
            total_events: 'Events',
            total_bookings: 'Bookings',
            visits: 'Visits',
            events_chart: 'Events Created',
            organizer_chart: 'Organizer Revenue',
            platform_chart: 'Platform Revenue',
            categories_title: 'Category Breakdown',
            col_category: 'Category',
            col_events: 'Events',
            col_share: 'Share',
            most_popular: 'Most Popular Events',
            worst_performing: 'Worst Performing Events',
            cancelled_events: 'Cancelled Events',
            countries: 'Visitor Countries',
            cities: 'Visitor Cities',
            devices: 'Devices',
            os: 'Operating System',
            realtime_title: 'Realtime',
            realtime_active: 'Active (last {minutes} min)',
            realtime_unique: 'Unique visitors',
            realtime_recent: 'Recent Activity',
            realtime_empty: 'No visits in the last {minutes} minutes.',
            col_event: 'Event',
            col_when: 'When',
            daily_title: 'Daily Visits (14 Days)',
            daily_visits: 'Visits',
            daily_unique: 'Unique',
            col_title: 'Event',
            col_bookings: 'Bookings',
            col_revenue: 'Revenue',
            col_city: 'City',
            col_count: 'Count',
            col_percent: 'Percent',
            col_date: 'Date',
            empty: 'No data yet.',
        },
        users: {
            title: 'Users',
            name: 'Name',
            email: 'Email',
            roles: 'Roles',
            actions: 'Actions',
            impersonate: 'Impersonate',
            suspend: 'Suspend',
            activate: 'Activate',
            delete: 'Delete',
            confirm_delete: 'Delete this user?',
            empty: 'No users yet.',
            impersonate_title: 'Confirm Impersonation',
            impersonate_hint: 'Enter your admin password to continue as {name}.',
            password_label: 'Admin Password',
            confirm: 'Log in as user',
            cancel: 'Cancel',
            search_placeholder: 'Search name or email…',
            filter_role: 'All roles',
            filter_status: 'All statuses',
            status_active: 'Active',
            status_suspended: 'Suspended',
            page_info: 'Page {page} of {last} · {total} users',
            prev: 'Previous',
            next: 'Next',
        },
        settings: {
            title: 'Platform Settings',
            tabs: {
                general: 'General',
                payment: 'Payment Gateway',
                whatsapp: 'WhatsApp',
                fee: 'Platform Fee',
            },
            general_title: 'General Settings',
            app_name: 'Application Name',
            contact_center: 'Contact Center',
            contact_email: 'Contact Email',
            payment_title: 'Payment Gateway',
            enabled: 'Enabled',
            provider: 'Provider',
            api_key: 'API Key',
            secret_key: 'Secret Key',
            secret_set: 'Stored (leave blank to keep)',
            whatsapp_title: 'WhatsApp Provider',
            token: 'Token',
            sender: 'Sender',
            fee_title: 'Platform Fee',
            fee_type: 'Type',
            fee_fixed: 'Fixed amount',
            fee_percent: 'Percentage (%)',
            fee_amount: 'Amount',
            save: 'Save',
            saving: 'Saving...',
        },
        catalog: {
            add: 'Add',
            save: 'Save',
            delete: 'Delete',
            cancel: 'Cancel',
            edit: 'Edit',
            name: 'Name',
            slug: 'Slug',
            name_en: 'Name (EN)',
            active: 'Active',
            quota: 'Quota',
            amount: 'Price',
            label: 'Label',
            empty: 'No data yet.',
        },
    },
};

export type AdminLanguage = 'id' | 'en';
export const defaultAdminLanguage: AdminLanguage = 'en';
