export const authTexts = {
    login: {
        title: 'Selamat Datang Kembali',
        subtitle: 'Silakan masuk ke akun Anda untuk melanjutkan.',
        email_label: 'Alamat Email',
        password_label: 'Kata Sandi',
        remember_me: 'Ingat saya',
        forgot_password: 'Lupa kata sandi?',
        submit_button: 'Masuk Sekarang',
        no_account: 'Belum punya akun?',
        register_link: 'Daftar di sini',
        otp_login_link: 'Masuk dengan Kode OTP',
        or_continue_with: 'Atau lanjut dengan',
        login_google: 'Google',
        login_facebook: 'Facebook',
        magic_link_button: 'Kirim Tautan Login',
        magic_link_subtitle: 'Masuk instan tanpa kata sandi via email.',
    },
    register: {
        title: 'Buat Akun Baru',
        subtitle: 'Bergabunglah dengan komunitas event kami.',
        name_label: 'Nama Lengkap',
        email_label: 'Alamat Email',
        password_label: 'Kata Sandi',
        confirm_password_label: 'Konfirmasi Kata Sandi',
        submit_button: 'Daftar Sekarang',
        has_account: 'Sudah punya akun?',
        login_link: 'Masuk di sini',
    },
    otp: {
        title: 'Verifikasi Kode OTP',
        subtitle: 'Masukan kode 6 digit yang dikirim ke email Anda.',
        otp_label: 'Kode OTP',
        submit_button: 'Verifikasi & Masuk',
        resend_text: 'Tidak menerima kode?',
        resend_link: 'Kirim ulang',
        back_to_login: 'Kembali ke Login',
    },
    common: {
        loading: 'Memproses...',
        error_title: 'Terjadi Kesalahan',
        success_title: 'Berhasil',
    },
    validation: {
        required: 'Field ini wajib diisi.',
        email: 'Format email tidak valid.',
        password_min: 'Kata sandi minimal 8 karakter.',
        password_mismatch: 'Konfirmasi kata sandi tidak cocok.',
    }
};
