export const bookingTexts = {
    id: {
        transaction: {
            title: 'Data Peserta',
            subtitle: 'Masukkan nama peserta untuk setiap tiket yang dipesan.',
            mode_label: 'Cara Pengisian',
            mode_individual: 'Isi per Peserta',
            mode_individual_desc: 'Nama dimasukkan satu per satu',
            mode_representative: 'Gunakan Perwakilan',
            mode_representative_desc: 'Satu nama mewakili seluruh pesanan',
            attendee_label: 'Peserta {n}',
            name_label: 'Nama',
            name_placeholder: 'Nama lengkap peserta',
            email_label: 'Email (opsional)',
            email_placeholder: 'email@contoh.com',
            phone_label: 'WhatsApp (opsional)',
            phone_placeholder: 'contoh: 081234567890',
            representative_name_label: 'Nama Perwakilan',
            representative_email_label: 'Email Perwakilan (opsional)',
            contact_title: 'Kontak Penerima Tiket',
            contact_hint: 'Tiket dan QR akan dikirim ke email ini. Tidak perlu membuat akun.',
            contact_name_label: 'Nama Kontak',
            contact_email_label: 'Email Kontak',
            order_summary: 'Ringkasan Pesanan',
            quantity: 'Jumlah',
            total: 'Total',
            continue: 'Lanjut ke Pembayaran',
            processing: 'Memproses...',
            back: 'Kembali ke Event',
            attendee_required: 'Nama peserta wajib diisi.',
        },
        pay: {
            title: 'Metode Pembayaran',
            subtitle: 'Selesaikan pembayaran untuk mengonfirmasi tiket Anda.',
            booking_number: 'Nomor Booking',
            order_summary: 'Ringkasan Pesanan',
            total: 'Total',
            choose_method: 'Pilih Metode Pembayaran',
            pay_now: 'Bayar Sekarang',
            paying: 'Memproses...',
            sandbox_note:
                'Pembayaran disimulasikan untuk lingkungan demo — tidak ada transaksi nyata yang terjadi.',
            back: 'Kembali ke Event',
            quantity: 'Jumlah',
            secure: 'Transaksi aman & terenkripsi',
        },
        show: {
            title: 'Detail Booking',
            subtitle: 'Rincian pemesanan tiket Anda.',
            booking_number: 'Nomor Booking',
            status_label: 'Status Booking',
            payment_status_label: 'Status Pembayaran',
            payment_method_label: 'Metode Pembayaran',
            event_label: 'Event',
            tickets_label: 'Tiket',
            total: 'Total',
            quantity: 'Jumlah',
            view_event: 'Lihat Event',
            complete_payment: 'Selesaikan Pembayaran',
            free_notice: 'Booking gratis — tiket Anda langsung terkonfirmasi.',
            status: {
                pending: 'Menunggu Pembayaran',
                confirmed: 'Terkonfirmasi',
                cancelled: 'Dibatalkan',
                refunded: 'Dana Kembali',
            },
            payment: {
                unpaid: 'Belum Dibayar',
                paid: 'Dibayar',
                refunded: 'Dana Kembali',
                free: 'Gratis',
            },
        },
    },
    en: {
        transaction: {
            title: 'Attendee Details',
            subtitle: 'Enter attendee names for each ticket in your order.',
            mode_label: 'Entry Mode',
            mode_individual: 'Per Attendee',
            mode_individual_desc: 'Enter names one by one',
            mode_representative: 'Use a Representative',
            mode_representative_desc: 'One name covers the whole order',
            attendee_label: 'Attendee {n}',
            name_label: 'Name',
            name_placeholder: 'Attendee full name',
            email_label: 'Email (optional)',
            email_placeholder: 'email@example.com',
            phone_label: 'WhatsApp (optional)',
            phone_placeholder: 'e.g. 081234567890',
            representative_name_label: 'Representative Name',
            representative_email_label: 'Representative Email (optional)',
            contact_title: 'Ticket Recipient Contact',
            contact_hint: 'Tickets and QR codes will be emailed here. No account needed.',
            contact_name_label: 'Contact Name',
            contact_email_label: 'Contact Email',
            order_summary: 'Order Summary',
            quantity: 'Quantity',
            total: 'Total',
            continue: 'Continue to Payment',
            processing: 'Processing...',
            back: 'Back to Event',
            attendee_required: 'Attendee name is required.',
        },
        pay: {
            title: 'Payment Method',
            subtitle: 'Complete payment to confirm your tickets.',
            booking_number: 'Booking Number',
            order_summary: 'Order Summary',
            total: 'Total',
            choose_method: 'Choose a Payment Method',
            pay_now: 'Pay Now',
            paying: 'Processing...',
            sandbox_note:
                'Payment is simulated for this demo environment — no real transaction occurs.',
            back: 'Back to Event',
            quantity: 'Quantity',
            secure: 'Secure & encrypted transaction',
        },
        show: {
            title: 'Booking Details',
            subtitle: 'Your ticket order summary.',
            booking_number: 'Booking Number',
            status_label: 'Booking Status',
            payment_status_label: 'Payment Status',
            payment_method_label: 'Payment Method',
            event_label: 'Event',
            tickets_label: 'Tickets',
            total: 'Total',
            quantity: 'Quantity',
            view_event: 'View Event',
            complete_payment: 'Complete Payment',
            free_notice: 'Free booking — your ticket is confirmed instantly.',
            status: {
                pending: 'Awaiting Payment',
                confirmed: 'Confirmed',
                cancelled: 'Cancelled',
                refunded: 'Refunded',
            },
            payment: {
                unpaid: 'Unpaid',
                paid: 'Paid',
                refunded: 'Refunded',
                free: 'Free',
            },
        },
    },
};

export type BookingLanguage = 'id' | 'en';
export const defaultBookingLanguage: BookingLanguage = 'en';
