export const eventTexts = {
    id: {
        create: {
            title: 'Buat Event Baru',
            subtitle: 'Lengkapi detail event yang akan Anda selenggarakan.',
            // Event type
            type_label: 'Jenis Event',
            category_label: 'Kategori Event',
            city_label: 'Kota',
            type_offline: 'Offline',
            type_offline_desc: 'Event tatap muka di lokasi fisik',
            type_online: 'Online',
            type_online_desc: 'Event via Zoom, Google Meet, dll.',
            type_hybrid: 'Hybrid',
            type_hybrid_desc: 'Kombinasi offline & online',
            // Fields
            title_label: 'Nama Event',
            title_placeholder: 'contoh: Konser Musik Indie 2026',
            description_label: 'Deskripsi',
            description_placeholder: 'Ceritakan detail event Anda: agenda, pembicara, apa yang didapat peserta...',
            venue_name_label: 'Nama Lokasi',
            venue_name_placeholder: 'contoh: Balai Kartini, Jakarta',
            venue_address_label: 'Alamat Lengkap',
            venue_address_placeholder: 'Jalan, kota, kode pos...',
            meeting_link_label: 'Tautan Meeting',
            meeting_link_placeholder: 'https://zoom.us/j/...',
            link_now: 'Isi Sekarang',
            link_later: 'Masukkan Nanti',
            link_later_hint: 'Tautan bisa diisi nanti dari daftar event, lalu dikirim ke email/WhatsApp peserta.',
            latitude_label: 'Latitude',
            latitude_placeholder: 'opsional, contoh: -6.2088',
            longitude_label: 'Longitude',
            longitude_placeholder: 'opsional, contoh: 106.8456',
            start_date_label: 'Mulai',
            end_date_label: 'Berakhir',
            capacity_label: 'Kapasitas Peserta',
            capacity_placeholder: 'opsional, kosongkan jika tak terbatas',
            // Tickets
            tickets_label: 'Tiket',
            tickets_hint: 'Atur jenis tiket, harga, kuota, dan periode penjualannya.',
            ticket_number: 'Tiket {n}',
            ticket_add: 'Tambah Tiket',
            ticket_remove: 'Hapus',
            ticket_name_label: 'Nama Tiket',
            ticket_name_placeholder: 'contoh: Early Bird, Regular, VIP',
            ticket_description_label: 'Deskripsi',
            ticket_description_placeholder: 'opsional, contoh: termasuk merchandise & konsumsi',
            ticket_price_label: 'Harga (Rp)',
            ticket_price_placeholder: '0 untuk gratis',
            ticket_free_hint: 'Isi 0 untuk tiket gratis.',
            ticket_quantity_label: 'Kuota',
            ticket_quantity_placeholder: 'jumlah tiket tersedia',
            ticket_limits_label: 'Batas per Pesanan',
            ticket_min_label: 'Min.',
            ticket_max_label: 'Maks.',
            ticket_window_label: 'Periode Penjualan (Opsional)',
            ticket_sale_starts_label: 'Mulai Dijual',
            ticket_sale_ends_label: 'Berhenti Dijual',
            ticket_active_label: 'Tiket aktif dijual',
            ticket_active_hint: 'Nonaktifkan untuk menyembunyikan tiket dari peserta.',
            ticket_error_required: 'Minimal satu tiket wajib diisi.',
            image_label: 'Banner Event',
            image_hint: 'PNG/JPG maks. 2MB (opsional)',
            image_current: 'Banner saat ini',
            image_replace: 'Ganti banner',
            location_section: 'Titik Lokasi (Opsional)',
            location_hint: 'Koordinat untuk peta, biarkan kosong jika tidak perlu.',
            // Status
            status_label: 'Status Publikasi',
            status_draft: 'Simpan Draft',
            status_draft_desc: 'Belum terlihat oleh peserta',
            status_published: 'Publikasikan',
            status_published_desc: 'Langsung tampil ke peserta',
            // WhatsApp delivery
            whatsapp_label: 'Kirim Tiket via WhatsApp',
            whatsapp_hint:
                'Peserta bisa menerima QR tiket lewat WhatsApp. Menggunakan kuota WhatsApp penyelenggara — top up di dashboard.',
            // Actions
            submit: 'Buat Event',
            submitting: 'Menyimpan...',
            cancel: 'Batal',
        },
        edit: {
            title: 'Edit Event',
            subtitle: 'Perbarui detail event Anda.',
        },
        show: {
            back_home: 'Kembali ke Beranda',
            edit_event: 'Edit Event',
            draft_badge: 'Draft',
            cancelled_badge: 'Dibatalkan',
            type_offline: 'Offline',
            type_online: 'Online',
            type_hybrid: 'Hybrid',
            date_range: '{start} — {end}',
            venue: 'Lokasi',
            meeting_link: 'Tautan Meeting',
            join: 'Gabung',
            capacity: 'Kapasitas',
            capacity_value: '{count} peserta',
            unlimited: 'Tidak terbatas',
            full: 'Penuh',
            tickets_title: 'Tiket Tersedia',
            free: 'Gratis',
            remaining: '{count} tersisa',
            sold_out: 'Habis',
            min_order: 'Min. {count}',
            max_order: 'Maks. {count}',
            no_tickets: 'Belum ada tiket tersedia.',
            organized_by: 'Diselenggarakan oleh',
            location_title: 'Lokasi',
            view_map: 'Lihat Peta',
            book_now: 'Pesan Sekarang',
            booking: 'Memproses...',
            login_to_book: 'Masuk untuk Memesan',
            organizer_cannot_book: 'Anda adalah penyelenggara event ini — tidak dapat membeli tiket.',
            select_tickets: 'Pilih tiket untuk melanjutkan',
            total: 'Total',
            event_full: 'Event sudah penuh',
            event_ended: 'Event sudah berakhir',
            attendees_registered: '{count} orang sudah mendaftar',
            rating_count: '{count} penilaian',
            no_rating: 'Belum ada penilaian',
            past_events: 'Event Sebelumnya',
            review_title: 'Beri Penilaian',
            review_subtitle: 'Bagaimana pengalaman Anda mengikuti event ini?',
            review_placeholder: 'Ceritakan pengalaman Anda (opsional)',
            review_submit: 'Kirim Penilaian',
            review_submitting: 'Mengirim...',
            my_review_title: 'Penilaian Anda',
        },
        analytics: {
            title: 'Analitik Event',
            subtitle: 'Pantau perkembangan penjualan dan kehadiran event Anda.',
            back: 'Kembali ke Event',
            kpi_revenue: 'Pendapatan',
            kpi_sold: 'Tiket Terjual',
            kpi_sell_through: 'Terjual',
            kpi_confirmed: 'Booking Terkonfirmasi',
            kpi_pending: 'Menunggu Pembayaran',
            kpi_checked_in: 'Sudah Check-in',
            kpi_remaining: 'Sisa Kuota',
            kpi_of_quota: 'dari {count} kuota',
            tickets_title: 'Performa per Tiket',
            tickets_empty: 'Belum ada tiket.',
            col_ticket: 'Tiket',
            col_price: 'Harga',
            col_quota: 'Kuota',
            col_sold: 'Terjual',
            col_remaining: 'Sisa',
            col_revenue: 'Pendapatan',
            timeline_title: 'Tren Penjualan (14 Hari)',
            timeline_bookings: 'booking',
            timeline_empty: 'Belum ada penjualan.',
            status_draft: 'Draft',
            status_published: 'Published',
            status_cancelled: 'Dibatalkan',
        },
        index: {
            title: 'Event Saya',
            subtitle: 'Kelola event dan tautan meeting Anda.',
            empty_title: 'Belum Ada Event',
            empty_desc: 'Event yang Anda buat akan tampil di sini.',
            create_event: 'Buat Event',
            view: 'Lihat',
            edit: 'Edit',
            publish: 'Publikasikan',
            cancel_event: 'Batalkan',
            delete_event: 'Hapus',
            delete_confirm: 'Hapus event ini?',
            // Badges & labels
            status_draft: 'Draft',
            status_published: 'Published',
            status_cancelled: 'Dibatalkan',
            type_offline: 'Offline',
            type_online: 'Online',
            type_hybrid: 'Hybrid',
            confirmed_bookings: '{count} peserta terkonfirmasi',
            starts: 'Mulai {date}',
            link_label: 'Tautan Meeting',
            link_set: 'Terisi',
            link_pending: 'Belum Diisi',
            // Actions
            stats: 'Statistik',
            set_link: 'Isi Tautan',
            save_link: 'Simpan',
            saving: 'Menyimpan...',
            send_link: 'Kirim ke Peserta',
            sending_link: 'Mengirim...',
            link_input_placeholder: 'https://zoom.us/j/...',
            no_attendees_hint: 'Belum ada peserta terkonfirmasi',
            // Pagination
            page_info: 'Halaman {page} dari {last} — {total} event',
            prev_page: 'Sebelumnya',
            next_page: 'Berikutnya',
        },
    },
    en: {
        create: {
            title: 'Create New Event',
            subtitle: "Fill in the details of the event you're organizing.",
            type_label: 'Event Type',
            category_label: 'Event Category',
            city_label: 'City',
            type_offline: 'Offline',
            type_offline_desc: 'In-person event at a physical venue',
            type_online: 'Online',
            type_online_desc: 'Event via Zoom, Google Meet, etc.',
            type_hybrid: 'Hybrid',
            type_hybrid_desc: 'Combination of offline & online',
            title_label: 'Event Name',
            title_placeholder: 'e.g. Indie Music Festival 2026',
            description_label: 'Description',
            description_placeholder: 'Describe your event: agenda, speakers, what attendees will get...',
            venue_name_label: 'Venue Name',
            venue_name_placeholder: 'e.g. Balai Kartini, Jakarta',
            venue_address_label: 'Full Address',
            venue_address_placeholder: 'Street, city, postal code...',
            meeting_link_label: 'Meeting Link',
            meeting_link_placeholder: 'https://zoom.us/j/...',
            link_now: 'Enter Now',
            link_later: 'Add Later',
            link_later_hint: 'You can add the link later from your events list, then send it to attendees via email/WhatsApp.',
            latitude_label: 'Latitude',
            latitude_placeholder: 'optional, e.g. -6.2088',
            longitude_label: 'Longitude',
            longitude_placeholder: 'optional, e.g. 106.8456',
            start_date_label: 'Starts',
            end_date_label: 'Ends',
            capacity_label: 'Attendee Capacity',
            capacity_placeholder: 'optional, leave empty for unlimited',
            // Tickets
            tickets_label: 'Tickets',
            tickets_hint: 'Set ticket types, pricing, quota, and sale periods.',
            ticket_number: 'Ticket {n}',
            ticket_add: 'Add Ticket',
            ticket_remove: 'Remove',
            ticket_name_label: 'Ticket Name',
            ticket_name_placeholder: 'e.g. Early Bird, Regular, VIP',
            ticket_description_label: 'Description',
            ticket_description_placeholder: 'optional, e.g. includes merch & refreshments',
            ticket_price_label: 'Price (Rp)',
            ticket_price_placeholder: '0 for free',
            ticket_free_hint: 'Set to 0 for a free ticket.',
            ticket_quantity_label: 'Quota',
            ticket_quantity_placeholder: 'number of tickets available',
            ticket_limits_label: 'Limits per Order',
            ticket_min_label: 'Min.',
            ticket_max_label: 'Max.',
            ticket_window_label: 'Sale Period (Optional)',
            ticket_sale_starts_label: 'Sale Starts',
            ticket_sale_ends_label: 'Sale Ends',
            ticket_active_label: 'Ticket is on sale',
            ticket_active_hint: 'Turn off to hide the ticket from attendees.',
            ticket_error_required: 'At least one ticket is required.',
            image_label: 'Event Banner',
            image_hint: 'PNG/JPG max 2MB (optional)',
            image_current: 'Current banner',
            image_replace: 'Replace banner',
            location_section: 'Location Pin (Optional)',
            location_hint: 'Coordinates for the map, leave empty if not needed.',
            status_label: 'Publication Status',
            status_draft: 'Save as Draft',
            status_draft_desc: 'Not visible to attendees yet',
            status_published: 'Publish',
            status_published_desc: 'Immediately visible to attendees',
            // WhatsApp delivery
            whatsapp_label: 'Deliver Tickets via WhatsApp',
            whatsapp_hint:
                'Attendees can receive ticket QRs over WhatsApp. Uses the organizer WhatsApp quota — top up from the dashboard.',
            submit: 'Create Event',
            submitting: 'Saving...',
            cancel: 'Cancel',
        },
        edit: {
            title: 'Edit Event',
            subtitle: 'Update the details of your event.',
        },
        show: {
            back_home: 'Back to Home',
            edit_event: 'Edit Event',
            draft_badge: 'Draft',
            cancelled_badge: 'Cancelled',
            type_offline: 'Offline',
            type_online: 'Online',
            type_hybrid: 'Hybrid',
            date_range: '{start} — {end}',
            venue: 'Venue',
            meeting_link: 'Meeting Link',
            join: 'Join',
            capacity: 'Capacity',
            capacity_value: '{count} attendees',
            unlimited: 'Unlimited',
            full: 'Full',
            tickets_title: 'Available Tickets',
            free: 'Free',
            remaining: '{count} remaining',
            sold_out: 'Sold Out',
            min_order: 'Min. {count}',
            max_order: 'Max. {count}',
            no_tickets: 'No tickets available yet.',
            organized_by: 'Organized by',
            location_title: 'Location',
            view_map: 'View Map',
            book_now: 'Book Now',
            booking: 'Processing...',
            login_to_book: 'Log in to Book',
            organizer_cannot_book: "You organize this event — you can't buy tickets.",
            select_tickets: 'Select tickets to continue',
            total: 'Total',
            event_full: 'Event is full',
            event_ended: 'Event has ended',
            attendees_registered: '{count} people have registered',
            rating_count: '{count} reviews',
            no_rating: 'No reviews yet',
            past_events: 'Past Events',
            review_title: 'Leave a Review',
            review_subtitle: 'How was your experience at this event?',
            review_placeholder: 'Share your experience (optional)',
            review_submit: 'Submit Review',
            review_submitting: 'Submitting...',
            my_review_title: 'Your Review',
        },
        analytics: {
            title: 'Event Analytics',
            subtitle: 'Track sales and attendance progress for your event.',
            back: 'Back to Event',
            kpi_revenue: 'Revenue',
            kpi_sold: 'Tickets Sold',
            kpi_sell_through: 'Sold',
            kpi_confirmed: 'Confirmed Bookings',
            kpi_pending: 'Awaiting Payment',
            kpi_checked_in: 'Checked In',
            kpi_remaining: 'Remaining Quota',
            kpi_of_quota: 'of {count} quota',
            tickets_title: 'Per-Ticket Performance',
            tickets_empty: 'No tickets yet.',
            col_ticket: 'Ticket',
            col_price: 'Price',
            col_quota: 'Quota',
            col_sold: 'Sold',
            col_remaining: 'Remaining',
            col_revenue: 'Revenue',
            timeline_title: 'Sales Trend (14 Days)',
            timeline_bookings: 'bookings',
            timeline_empty: 'No sales yet.',
            status_draft: 'Draft',
            status_published: 'Published',
            status_cancelled: 'Cancelled',
        },
        index: {
            title: 'My Events',
            subtitle: 'Manage your events and meeting links.',
            empty_title: 'No Events Yet',
            empty_desc: 'Events you create will show up here.',
            create_event: 'Create Event',
            view: 'View',
            edit: 'Edit',
            publish: 'Publish',
            cancel_event: 'Cancel',
            delete_event: 'Delete',
            delete_confirm: 'Delete this event?',
            status_draft: 'Draft',
            status_published: 'Published',
            status_cancelled: 'Cancelled',
            type_offline: 'Offline',
            type_online: 'Online',
            type_hybrid: 'Hybrid',
            confirmed_bookings: '{count} confirmed attendees',
            starts: 'Starts {date}',
            link_label: 'Meeting Link',
            link_set: 'Set',
            link_pending: 'Pending',
            stats: 'Analytics',
            set_link: 'Add Link',
            save_link: 'Save',
            saving: 'Saving...',
            send_link: 'Send to Attendees',
            sending_link: 'Sending...',
            link_input_placeholder: 'https://zoom.us/j/...',
            no_attendees_hint: 'No confirmed attendees yet',
            // Pagination
            page_info: 'Page {page} of {last} — {total} events',
            prev_page: 'Previous',
            next_page: 'Next',
        },
    },
};

export type EventLanguage = 'id' | 'en';
export const defaultEventLanguage: EventLanguage = 'en';
