export const whatsappTexts = {
    id: {
        title: 'Kuota WhatsApp',
        subtitle: 'Top up kuota untuk mengirim tiket peserta lewat WhatsApp.',
        balance_label: 'Sisa Kuota',
        balance_unit: 'pesan',
        packages_title: 'Paket Top Up',
        package_quota: '{count} pesan WhatsApp',
        payment_title: 'Metode Pembayaran',
        topup: 'Top Up Sekarang',
        processing: 'Memproses...',
        history_title: 'Riwayat Top Up',
        history_empty: 'Belum ada top up.',
        history_package: 'Paket',
        history_quota: 'Kuota',
        history_amount: 'Jumlah',
        history_method: 'Metode',
        history_status: 'Status',
        history_date: 'Tanggal',
        status_paid: 'Berhasil',
        status_pending: 'Menunggu',
        note: 'Kuota dipakai 1 per tiket yang dikirim via WhatsApp. Pembayaran disimulasikan di lingkungan demo.',
        back: 'Kembali ke Dashboard',
    },
    en: {
        title: 'WhatsApp Quota',
        subtitle: 'Top up quota to send attendee tickets over WhatsApp.',
        balance_label: 'Remaining Quota',
        balance_unit: 'messages',
        packages_title: 'Top Up Packages',
        package_quota: '{count} WhatsApp messages',
        payment_title: 'Payment Method',
        topup: 'Top Up Now',
        processing: 'Processing...',
        history_title: 'Top Up History',
        history_empty: 'No top ups yet.',
        history_package: 'Package',
        history_quota: 'Quota',
        history_amount: 'Amount',
        history_method: 'Method',
        history_status: 'Status',
        history_date: 'Date',
        status_paid: 'Paid',
        status_pending: 'Pending',
        note: 'One quota unit is used per ticket sent over WhatsApp. Payment is simulated in this demo environment.',
        back: 'Back to Dashboard',
    },
};

export type WhatsAppLanguage = 'id' | 'en';
export const defaultWhatsAppLanguage: WhatsAppLanguage = 'en';
